<div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow" data-scroll-to-active="true">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item me-auto"><a class="navbar-brand" href="/"><span class="brand-logo">
                            </span>
                        <h2 class="brand-text">Stafeta Muntilor</h2>
                    </a></li>
                <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pe-0" data-bs-toggle="collapse"><i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i></a></li>
            </ul>
        </div>
        <div class="shadow-bottom"></div>
        <div class="main-menu-content">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['dashboard']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('dashboard', $stageid) }}"><i data-feather="grid"></i><span class="menu-title text-truncate" data-i18n="Dashboards">Dashboard</span></a></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['setup.index']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('setup.index', [$stageid]) }}"><i data-feather="tool"></i><span class="menu-title text-truncate" data-i18n="Configurare">Configurare</span></a></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['clubs.index', 'clubs.clubs.listbyteams']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('clubs.index', [$stageid]) }}"><i data-feather='users'></i><span class="menu-title text-truncate" data-i18n="Cluburi">Cluburi</span></a></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['teams.index', 'teams.order.start', 'import.index', 'import.teams_chipno_and_team_name_check']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('teams.index', [$stageid]) }}"><i data-feather="sliders"></i><span class="menu-title text-truncate" data-i18n="Echipe">Echipe</span></a></li>
                <li class=" navigation-header"><span data-i18n="">Cultural</span><i data-feather="more-horizontal"></i></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['cultural.index']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('cultural.index', [$stageid]) }}"><i data-feather="star"></i><span class="menu-title text-truncate" data-i18n="Cultural">Cultural</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Family">Categoria Family</span><i data-feather="more-horizontal"></i></li>
                    
                    <li class="nav-item @if(Request::path() === $stageid .'/knowledge/1') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', [$stageid, 1]) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/climb/1') active @endif"><a class="d-flex align-items-center" href="{{ route('climb.index', [$stageid, 1]) }}"><i data-feather="trending-up"></i><span class="menu-title text-truncate" data-i18n="Alpinism">Alpinism</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/orienteering/1') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', [$stageid, 1]) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/raidmontan/1') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', [$stageid, 1]) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/rankings/1' || Request::path() === $stageid .'/rankings/1/knowledge' || Request::path() === $stageid .'/rankings/1/climb'|| Request::path() === $stageid .'/rankings/1/orienteering' || Request::path() === $stageid .'/rankings/1/raidmontan' || Request::path() === $stageid .'/rankings/1/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', [$stageid, 1]) }}"><i data-feather="bar-chart-2"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Juniori">Categoria Juniori</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/knowledge/2') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', [$stageid, 2]) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/climb/2') active @endif"><a class="d-flex align-items-center" href="{{ route('climb.index', [$stageid, 2]) }}"><i data-feather="trending-up"></i><span class="menu-title text-truncate" data-i18n="Alpinism">Alpinism</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/orienteering/2') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', [$stageid, 2]) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/raidmontan/2') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', [$stageid, 2]) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/rankings/2' || Request::path() === $stageid .'/rankings/2/knowledge' || Request::path() === $stageid .'/rankings/2/climb'|| Request::path() === $stageid .'/rankings/2/orienteering' || Request::path() === $stageid .'/rankings/2/raidmontan' || Request::path() === $stageid .'/rankings/2/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', [$stageid, 2]) }}"><i data-feather="bar-chart-2"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Elite">Categoria Elite</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/knowledge/3') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', [$stageid, 3]) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/climb/3') active @endif"><a class="d-flex align-items-center" href="{{ route('climb.index', [$stageid, 3]) }}"><i data-feather="trending-up"></i><span class="menu-title text-truncate" data-i18n="Alpinism">Alpinism</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/orienteering/3') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', [$stageid, 3]) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/raidmontan/3') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', [$stageid, 3]) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/rankings/3' || Request::path() === $stageid .'/rankings/3/knowledge' || Request::path() === $stageid .'/rankings/3/climb'|| Request::path() === $stageid .'/rankings/3/orienteering' || Request::path() === $stageid .'/rankings/3/raidmontan' || Request::path() === $stageid .'/rankings/3/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', [$stageid, 3]) }}"><i data-feather="bar-chart-2"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Open">Categoria Open</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/knowledge/4') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', [$stageid, 4]) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/climb/4') active @endif"><a class="d-flex align-items-center" href="{{ route('climb.index', [$stageid, 4]) }}"><i data-feather="trending-up"></i><span class="menu-title text-truncate" data-i18n="Alpinism">Alpinism</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/orienteering/4') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', [$stageid, 4]) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/raidmontan/4') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', [$stageid, 4]) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/rankings/4' || Request::path() === $stageid .'/rankings/4/knowledge' || Request::path() === $stageid .'/rankings/4/climb'|| Request::path() === $stageid .'/rankings/4/orienteering' || Request::path() === $stageid .'/rankings/4/raidmontan' || Request::path() === $stageid .'/rankings/4/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', [$stageid, 4]) }}"><i data-feather="bar-chart-2"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Veterani">Categoria Veterani</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/knowledge/5') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', [$stageid, 5]) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/climb/5') active @endif"><a class="d-flex align-items-center" href="{{ route('climb.index', [$stageid, 5]) }}"><i data-feather="trending-up"></i><span class="menu-title text-truncate" data-i18n="Alpinism">Alpinism</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/orienteering/5') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', [$stageid, 5]) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/raidmontan/5') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', [$stageid, 5]) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/rankings/5' || Request::path() === $stageid .'/rankings/5/knowledge' || Request::path() === $stageid .'/rankings/5/climb'|| Request::path() === $stageid .'/rankings/5/orienteering' || Request::path() === $stageid .'/rankings/5/raidmontan' || Request::path() === $stageid .'/rankings/5/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', [$stageid, 5]) }}"><i data-feather="bar-chart-2"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>


                    <li class="navigation-header"><span data-i18n="Categoria Feminin">Categoria Feminin</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/knowledge/6') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', [$stageid, 6]) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/climb/6') active @endif"><a class="d-flex align-items-center" href="{{ route('climb.index', [$stageid, 6]) }}"><i data-feather="trending-up"></i><span class="menu-title text-truncate" data-i18n="Alpinism">Alpinism</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/orienteering/6') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', [$stageid, 6]) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/raidmontan/6') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', [$stageid, 6]) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/rankings/6' || Request::path() === $stageid .'/rankings/6/knowledge' || Request::path() === $stageid .'/rankings/6/climb'|| Request::path() === $stageid .'/rankings/6/orienteering' || Request::path() === $stageid .'/rankings/6/raidmontan' || Request::path() === $stageid .'/rankings/6/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', [$stageid, 6]) }}"><i data-feather="bar-chart-2"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Seniori">Categoria Seniori</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/knowledge/7') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', [$stageid, 7]) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/climb/7') active @endif"><a class="d-flex align-items-center" href="{{ route('climb.index', [$stageid, 7]) }}"><i data-feather="trending-up"></i><span class="menu-title text-truncate" data-i18n="Alpinism">Alpinism</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/orienteering/7') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', [$stageid, 7]) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/raidmontan/7') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', [$stageid, 7]) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === $stageid .'/rankings/7' || Request::path() === $stageid .'/rankings/7/knowledge' || Request::path() === $stageid .'/rankings/7/climb'|| Request::path() === $stageid .'/rankings/7/orienteering' || Request::path() === $stageid .'/rankings/7/raidmontan' || Request::path() === $stageid .'/rankings/7/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', [$stageid, 7]) }}"><i data-feather="bar-chart-2"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>


                <li class="navigation-header"><span data-i18n="Clasamente">Clasamente </span><i data-feather="more-horizontal"></i></li>
                <li class="nav-item @if(Request::path() === $stageid .'/rankings/general') active @endif"><a class="d-flex align-items-center" href="{{ route('rankings.general', $stageid) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">General Etapa</span></a></li>
                <li class="nav-item @if(Request::path() === $stageid .'/participants/rankingcumulatclubs') active @endif"><a class="d-flex align-items-center" href="{{ route('participants.rankingcumulatclubs') }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Cumulat Etape</span></a></li>
                <li class="navigation-header"><span data-i18n="Participanti">Participanti </span><i data-feather="more-horizontal"></i></li>
                <li class="nav-item @if(Request::path() === '/participants/list') active @endif"><a class="d-flex align-items-center" href="{{ route('participants.list') }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Alte Clasamente</span></a></li>
                <li class="nav-item @if(Request::path() === '/participants/'. $stageid .'/list') active @endif"><a class="d-flex align-items-center" href="{{ route('participants.stages.list', $stageid) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Participanti Etapa</span></a></li>
            </ul>
        </div>
    </div>