<div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow" data-scroll-to-active="true">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item me-auto"><a class="navbar-brand" href="/"><span class="brand-logo">
                            </span>
                        <h2 class="brand-text">Stafeta Muntilor</h2>
                    </a></li>
                <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pe-0" data-bs-toggle="collapse"><i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i></a></li>
            </ul>
        </div>
        <div class="shadow-bottom"></div>
        <div class="main-menu-content">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['dashboard']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('dashboard') }}"><i data-feather="home"></i><span class="menu-title text-truncate" data-i18n="Dashboards">Dashboard</span></a></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['setup.index']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('setup.index') }}"><i data-feather="home"></i><span class="menu-title text-truncate" data-i18n="Configurare">Configurare</span></a></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['clubs.index', 'clubs.clubs.listbyteams']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('clubs.index') }}"><i data-feather='bar-chart-2'></i><span class="menu-title text-truncate" data-i18n="Cluburi">Cluburi</span></a></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['teams.index', 'teams.order.start', 'import.index']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('teams.index') }}"><i data-feather="home"></i><span class="menu-title text-truncate" data-i18n="Echipe">Echipe</span></a></li>
                <li class=" navigation-header"><span data-i18n="">Cultural</span><i data-feather="more-horizontal"></i></li>
                <li class="{{ \App\Helpers\Navigation::isActiveRoute(['cultural.index']) }} nav-item"><a class="d-flex align-items-center" href="{{ route('cultural.index') }}"><i data-feather="home"></i><span class="menu-title text-truncate" data-i18n="Cultural">Cultural</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Family">Categoria Family</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === 'knowledge/1') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', 1) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === 'orienteering/1') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', 1) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === 'raidmontan/1') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', 1) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === 'rankings/1' || Request::path() === 'rankings/1/knowledge' || Request::path() === 'rankings/1/orienteering' || Request::path() === 'rankings/1/raidmontan' || Request::path() === 'rankings/1/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', 1) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Juniori">Categoria Juniori</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === 'knowledge/2') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', 2) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === 'orienteering/2') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', 2) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === 'raidmontan/2') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', 2) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === 'rankings/2' || Request::path() === 'rankings/2/knowledge' || Request::path() === 'rankings/2/orienteering' || Request::path() === 'rankings/2/raidmontan' || Request::path() === 'rankings/2/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', 2) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Elite">Categoria Elite</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === 'knowledge/3') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', 3) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === 'orienteering/3') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', 3) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === 'raidmontan/3') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', 3) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === 'rankings/3' || Request::path() === 'rankings/3/knowledge' || Request::path() === 'rankings/3/orienteering' || Request::path() === 'rankings/3/raidmontan' || Request::path() === 'rankings/3/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', 3) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Open">Categoria Open</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === 'knowledge/4') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', 4) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === 'orienteering/4') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', 4) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === 'raidmontan/4') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', 4) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === 'rankings/4' || Request::path() === 'rankings/4/knowledge' || Request::path() === 'rankings/4/orienteering' || Request::path() === 'rankings/4/raidmontan' || Request::path() === 'rankings/4/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', 4) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Veterani">Categoria Veterani</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === 'knowledge/5') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', 5) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === 'orienteering/5') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', 5) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === 'raidmontan/5') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', 5) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === 'rankings/5' || Request::path() === 'rankings/5/knowledge' || Request::path() === 'rankings/5/orienteering' || Request::path() === 'rankings/5/raidmontan' || Request::path() === 'rankings/5/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', 5) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>


                    <li class="navigation-header"><span data-i18n="Categoria Feminin">Categoria Feminin</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === 'knowledge/6') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', 6) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === 'orienteering/6') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', 6) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === 'raidmontan/6') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', 6) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === 'rankings/6' || Request::path() === 'rankings/6/knowledge' || Request::path() === 'rankings/6/orienteering' || Request::path() === 'rankings/6/raidmontan' || Request::path() === 'rankings/6/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', 6) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>

                    <li class="navigation-header"><span data-i18n="Categoria Seniori">Categoria Seniori</span><i data-feather="more-horizontal"></i></li>
                    <li class="nav-item @if(Request::path() === 'knowledge/7') active @endif"><a class="d-flex align-items-center" href="{{ route('knowledge.index', 7) }}"><i data-feather="book-open"></i><span class="menu-title text-truncate" data-i18n="Cunostinte Turistice">Cunostinte Turistice</span></a></li>
                    <li class="nav-item @if(Request::path() === 'orienteering/7') active @endif"><a class="d-flex align-items-center" href="{{ route('orienteering.index', 7) }}"><i data-feather="compass"></i><span class="menu-title text-truncate" data-i18n="Orientare">Orientare</span></a></li>
                    <li class="nav-item @if(Request::path() === 'raidmontan/7') active @endif"><a class="d-flex align-items-center" href="{{ route('raidmontan.index', 7) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Raid Montan">Raid Montan</span></a></li>
                    <li class="nav-item @if(Request::path() === 'rankings/7' || Request::path() === 'rankings/7/knowledge' || Request::path() === 'rankings/7/orienteering' || Request::path() === 'rankings/7/raidmontan' || Request::path() === 'rankings/7/generalcategory') active  @endif"><a class="d-flex align-items-center" href="{{ route('rankings.index_category', 7) }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">Clasamente</span></a></li>


                <li class="navigation-header"><span data-i18n="Clasamente">Clasamente </span><i data-feather="more-horizontal"></i></li>
                <li class="nav-item"><a class="d-flex align-items-center" href="{{ route('rankings.general') }}"><i data-feather="map"></i><span class="menu-title text-truncate" data-i18n="Clasamente">General</span></a></li>
            </ul>
        </div>
    </div>